import Head from 'next/head';
import React from 'react';
import { getAllPostsSupa } from '@/app/api';
import BlogList from '@/components/Blog/BlogList';
import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';
import Navbar from '@/components/NavBar/Navbar';
const PostPage = async ({ params }) => {
   const { slug } = params;
   const posts = (await getAllPostsSupa()).filter((post) =>
      post.meta.tags.includes(slug)
   );
   return (
      <>
         <Head>
            <title>Tag: {slug}</title>
            <meta name='description' content='Generated by create next app' />
            <meta
               name='viewport'
               content='width=device-width, initial-scale=1'
            />
            <link rel='icon' href='/favicon.ico' />
         </Head>
         <main
            className={
               'flex flex-col pt-2 px-6 max-w-[50rem] align-center m-auto min-h-[600px] w-full'
            }
         >
            <Navbar />
            <Header title={slug ?? 'tag'} />
            <BlogList posts={posts.map((post) => post.meta)} />
         </main>
         <Footer></Footer>
      </>
   );
};

export const getStaticPaths = async () => {
   const posts = await getAllPostsSupa();
   // At this point if we map tags, we should have an array of arrays. Lets try and
   // flatten these arrays into a set
   const tags = new Set(posts.map((post) => post.meta.tags).flat());
   const paths = Array.from(tags).map((tag) => ({ params: { slug: tag } }));
   return {
      paths,
      fallback: 'blocking',
   };
};
export default PostPage;
