import Head from 'next/head'
import React from 'react'
import BlogList from '../../../components/Blog/BlogList'
import Footer from '../../../components/Footer'
import Header from '../../../components/Header'
import Navbar from '../../../components/Navbar'
import mainStyles from '../../../styles/Home.module.css'
import { getAllPostsSupa } from '../../api'
const PostPage = ({ slug, posts}) => {
  return (
    <>
      <Head>
        <title>Tag: {slug}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={mainStyles.main + ' main-body'}>
        <Navbar/>
        <Header title={slug ?? 'tag'} />
        <BlogList posts={posts}/>
      </main>
      <Footer></Footer>
    </>
  )
}
export const getStaticProps = async ({params}) => {
  const {slug} = params;
  const posts = (await getAllPostsSupa()).filter(post => post.meta.tags.includes(slug));

  return {
    props: {
      slug,
      posts: posts.map((post) => post.meta)
    },
    revalidate: 10, // Revalidate pagee every 10 seconds
  }
}

export const getStaticPaths = async () => {
  const posts = await getAllPostsSupa();
  // At this point if we map tags, we should have an array of arrays. Lets try and
  // flatten these arrays into a set
  const tags = new Set(posts.map((post) => post.meta.tags).flat());
  const paths = Array.from(tags).map((tag) => ({params: {slug: tag}}));
  return {
    paths,
    fallback: 'blocking',
  }
}
export default PostPage